config:
    paths:
        'oroapruve/js/app/components/payment-method-component': 'bundles/oroapruve/js/app/components/payment-method-component.js'
        'oroapruve/js/lib/apruvejs-test': '//test.apruve.com/js/v4/apruve.js'
        'oroapruve/js/lib/apruvejs-prod': '//app.apruve.com/js/v4/apruve.js'
    shim:
        'oroapruve/js/lib/apruvejs-test':
            exports: 'apruve'
        'oroapruve/js/lib/apruvejs-prod':
            exports: 'apruve'

build:
    paths:
        'oroapruve/js/lib/apruvejs-test': 'empty:'
